"""Added links table

Revision ID: ba6f832ad6c7
Revises: 
Create Date: 2022-02-26 21:16:09.061068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6f832ad6c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_link_id', sa.String(length=8), nullable=False),
    sa.Column('original_url', sa.String(length=255), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_short_link_id'), 'links', ['short_link_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_short_link_id'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
