"""Added Stats Table

Revision ID: cd0b4bbcd7bb
Revises: ba6f832ad6c7
Create Date: 2022-02-27 08:29:07.518961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0b4bbcd7bb'
down_revision = 'ba6f832ad6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('links', sa.Column('stat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'links', 'stats', ['stat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_column('links', 'stat_id')
    op.drop_table('stats')
    # ### end Alembic commands ###
